name: GleasonXAI
channels:
  - conda-forge
dependencies:
  - python=3.10.13
  - pip=23.1.0
  - pytorch::pytorch=2.1.1
  - pytorch::torchvision=0.16.1
  - pytorch::torchaudio=2.1.1
  - pip:

    - pandas==2.1.1
    - scikit-learn==1.3.2
    - scipy==1.11.3

    - matplotlib==3.8.0
    - seaborn==0.13.2
    - ipywidgets==8.1.2

    - opencv-python==4.8.1.78
    - pillow==9.5.0
    - scikit-image==0.22.0
    - segmentation-models-pytorch==0.3.3
    - albumentations==1.3.1
    - monai==1.3.0
    - wandb==0.17.1
    

    - hydra-core==1.3.2
    - hydra-optuna-sweeper==1.2.0
    - tensorboard==2.16.2
    - timm==0.9.2
    - torchmetrics==1.3.0
    - pytorch-lightning==2.1.3
    

    - ipykernel
    - ipython
    

    - statsmodels==0.14.2
